language: cpp
compiler: gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CXX=g++-7"


before_install:
    - eval "${MATRIX_EVAL}"
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt-get update -q
    - sudo apt-get install python3.6 -y

script: make && make test
