language: cpp


matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-7
            - python3.6
      env:
         - MATRIX_EVAL="CXX=g++-7"


before_script:
    - eval "${MATRIX_EVAL}"
    - alias python=python3
    - shopt -s expand_aliases


script: 
    - make && make test
