language: cpp
compiler: gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - python3.6
      env:
         - MATRIX_EVAL="CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script: make && make test
