language: cpp


matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-7
            - python3.6
      env:
         - MATRIX_EVAL="CXX=g++-7"

-before_install:
    - shopt -s expand_aliases
    - eval "${MATRIX_EVAL}"
    - alias python=python3


script: make && make test
